### ISSUE TITLE
1.1.2 crashes with Sodium if "fullscreen mode" config is null

### ISSUE THREAD

**Issue by Longie520** [DeeChael/Concentration#12]
[crash-2024-06-21_18.51.46-client.txt](https://github.com/user-attachments/files/15925566/crash-2024-06-21_18.51.46-client.txt)

System: M1 MacBook Pro
Java: Minecraft Bundled Java 21

1.1.2 says to have fixed conflict with Sodium Extra, but it still crashes

**Comment by DeeChael** [comment]
Can you provide more steps about what did you do because there isn't anything useful in the crash report and I need more details.
In my test the game didn't crash you can see the time in the right bottom corner (UTC +8)
![image](https://github.com/DeeChael/Concentration/assets/63186003/c5e08dd9-3640-4762-99ef-59ee48511c1a)

**Comment by Longie520** [comment]
I found the real problem...
When launching with Concentration 1.1.2 and Sodium in a BRAND NEW instance (or when updating from Concentration 1.1.1 to 1.1.2), the config file is not handled correctly if it's empty or missing certain lines. This results in a crash when clicking into the Sodium video settings screen

I was able to reproduce it again and it happens without Sodium Extra and Reese's Sodium Options

== My case ==

My old config for 1.1.1:
```
{
  "customized": true,
  "related": false,
  "x": 80,
  "y": 113,
  "width": 1352,
  "height": 728
}
```

My current config for 1.1.2:
```
{
  "customized": true,
  "related": false,
  "x": 80,
  "y": 113,
  "width": 1352,
  "height": 728,
  "fullscreen": "BORDERLESS"
}
```

The difference is that the line ```"fullscreen": "BORDERLESS"``` is not in the old config file, and it crashes with Sodium; same with an empty config file. 

But if the config file is complete (second example), the game runs fine without crashing.

This happens on MacBook; not sure if it happens on any other OSs.


* I hope that made sense, I don't know how to describe it any better :)

**Comment by Longie520** [comment]
Here is the newer version of crash report
https://paste.ee/p/xHJF3

Brand new instance with FAPI, Sodium and Concentration 1.1.2

No older/existing configs in the config folder

**Comment by DeeChael** [comment]
> Here is the newer version of crash report https://paste.ee/p/xHJF3
> 
> Brand new instance with FAPI, Sodium and Concentration 1.1.2
> 
> No older/existing configs in the config folder

I think you are right, I'll add a default value for the config to prevent the crashing, thanks for your report and testing!

**Comment by DeeChael** [comment]
Oh, I actually found that the config should have a default value but I forgot to add it. Sorry for that

**Comment by DeeChael** [comment]
Should fix in 1.1.3 and my test works but I don't sure if macOS also, need further feedback

**Comment by DeeChael** [comment]
a user in Fabulously Optimized discord server had also met this issue and he tried 1.1.3 and no issue here so i just need to know if macos also fixed (I think there is nothing different because this is not a issue relateing to system)
![image](https://github.com/DeeChael/Concentration/assets/63186003/2a9be341-cd57-49ef-bc3f-2356d0ea8439)

**Comment by Longie520** [comment]
no longer an issue on macos!
