### ISSUE TITLE
Add ability to toggle 'always on top' mode

### ISSUE THREAD

**Issue by DannyDan4** [DeeChael/Concentration#18]
I cannot place other windows on top of Minecraft while the game is running with this addon, behaving similarly to the 'always on top' feature of something like task manager

**Comment by DeeChael** [comment]
As borderless fullscreen is actually just a windowed app, the game will behave like a normal window. For example, if you have two windows that overlap each other, when you focus on one of them, the other one will be covered.

I mean, with borderless fullscreen mod, you cant place other windows on top of Minecraft, because this is not a feature provided by the mod, but the system.

But u can use Microsoft's PowerToys, in PowerToys, there is a tool called Always On Top.

**Comment by DannyDan4** [comment]
I guess I didn't clarify entirely; basically, the window was refusing to let -anything- sit on top of it, indicating to me that it may be misconfigured to behave like that without a toggle, as the 'cubes without borders' mod does not have this same issue.
