### ISSUE TITLE
Toogling fullscreen changes the game Monitor

### ISSUE THREAD

**Issue by f-michaut** [DeeChael/Concentration#2]
So I have 2 monitors, and I like to use the right one for playing. 
When I toggle full screen with this mod, it forces the game to the first monitor (the left one).

The issue is that I cannot move the window to the other monitor anymore (cause its a windowed fullscreen), if I use window's shortcuts to do so, the window will be cropped (since the title bar will be made visible again by windows).

Could you make it so that it respects the current monitor being used ?

**Comment by DeeChael** [comment]
Fixed in 1.0.4.

But another problem appears: If you switch to fullscreen in the second monitor and you switch back to windowed mode, the window will be moved to the first monitor, though it doesn't affect the fullscreen experience, but I think it is not good. And I'll open a new issue to talk about that problem.

Thanks for your report!

**Comment by f-michaut** [comment]
Oh my god that was a quick fix ! Thank you so much

Yeah the other issue is probably a bit annoying, but since we can at least move the windowed window on the proper monitor afterwards, its probably fine for now

Thank you !

**Comment by DeeChael** [comment]
> Oh my god that was a quick fix ! Thank you so much
> 
> Yeah the other issue is probably a bit annoying, but since we can at least move the windowed window on the proper monitor afterwards, its probably fine for now
> 
> Thank you !

The issues I mentioned has been fixed in 1.0.6, thanks for your support!
