### ISSUE TITLE
Window will be moved to the primary monitor after swtiching from fullscreen mode to windowed mode

### ISSUE THREAD

**Issue by DeeChael** [DeeChael/Concentration#4]

**Comment by DeeChael** [comment]
Fixed

**Comment by idiot-shinuki** [comment]
Getting a similar issue in Minecraft 1.21.1 on version 1.1.8 for neoforge. I open the game on my primary monitor but when I turn on fullscreen, it's forced to my second monitor. Maybe add an option to select which monitor to use? i'm running on linux if it helps.

Some extra details:
Changing the height to 1048 seems to allow it to fit on the primary display, I suspect this is because of the top bar on Gnome Desktop Environments (which is only present on the primary display). Other borderless fullscreen mods ignore it and render over it in order to make use of the entire screen. This modpack (All The Mods 10) has Sinytra Connector so I'll test if one of the fabric borderless fullscreen mods work on here until there's a fix for this one (i always prefer mods that are native to the mod loader i'm using)
